### PR TITLE
Header & Footer Work

### PR DESCRIPTION
**Pull request by mitdralla**
- Created new components for header and footer. 
- Made footer links dynamic and am loading them in through the config file with a loop. 
- Cleaned up and removed material design elements from header and footer.
- Link positioning

### CODE REVIEW

**Comment by mitdralla** [comment]
- Added layout enhancements
- Added Jumbotron
- Added Sidebar
- Added Main Body Content Window

**Comment by mitdralla** [comment]
- Added new placeholder pages, made modification so no page load required
- Fixed travis build for unused constant
- Now using <Link to=""> for routes

**Comment by mitdralla** [comment]
- Page placeholders for Sidebar

**Review by gregnorth — APPROVED** [review]
LGTM

**Pull request merged**
